README.md

READMEに記述されているpokepaylibのバージョンを最新に更新しました。

READMEに記述されているpokepaylibのバージョンを最新に更新

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/JsonConverter.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Parameter.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Request.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Response.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/JwtResult.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/PrivateMoney.java
sample/src/main/java/jp/pokepay/pokepay/LowLevelAPITests.java
sample/src/main/java/jp/pokepay/pokepay/SubsetOfAccount.java
sample/src/main/java/jp/pokepay/pokepay/View03Activity.java
sample/src/main/res/layout/activity_view03.xml

14 support private money api new feature

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/Request.java
sample/src/main/java/jp/pokepay/pokepay/LowLevelAPITests.java

Fixed a bug that GET parameter loss.

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/Check.java

modify response type of point_expires_in_days
Date to Int

fix point_ecpires_in_days to int

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Account/GetAccountCouponDetail.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Account/GetAccountCoupons.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Account/PatchAccountCouponDetail.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/PrivateMoney/GetPrivateMoneyCoupons.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithBill.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithCashtray.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithJwt.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/Coupon.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/CouponDetail.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/PaginatedCoupons.java
sample/build.gradle
sample/src/main/java/jp/pokepay/pokepay/LowLevelAPITests.java
sample/src/main/java/jp/pokepay/pokepay/View03Activity.java
sample/src/main/res/layout/activity_view03.xml

Add following feature: 
- GET /accounts/{account_id}/coupons： list of coupons that have already been received
- GET /accounts/{account_id}/coupons/{coupon_id} : get a coupon detail
- PATCH /accounts/{account_id}/coupons/{coupon_id}: receive a coupon
- GET /private-moneys/{private_money_id}/coupons: list of coupons can receive
- POST /transactions: make payment transaction using a coupon
- #/components/schemas/PostTransactionJwtRequest
- #/components/schemas/PostTransactionBillRequest
- #/components/schemas/PostTransactionCashtrayRequest

Add Coupon feature

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java

modify scanTokenBLE

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/PrivateMoney/GetPrivateMoney.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/PrivateMoney.java

@taniryo-kun
For [this custom domain issue](https://github.com/pokepay/pokepay-server/issues/2936)
How to get client with custom domain
```java
// SetEnv //
Pokepay.setEnv(Env.DEVELOPMENT); // or Env.SANDBOX, Env.PRODUCTION
// get client //
new Thread(new Runnable() {
@Override
public void run() {
try {
Pokepay.Client client = Pokepay.Client.withCustomDomain("ZhwMsfoAyWZMGrCAKrrofmwYHV82GkUcf3kYSZYYf1oDKVvFAPIKuefyQoc1KDVr", context, "private-money-id");
} catch (ProcessingError err) {
// err is Runtime error.
// The caller may be wrong.
// Please check your code.
} catch (BankRequestError err) {
// err is mainly API Errors
// It occurres when the status code is other than 2xx (in BankAPI, MessagingAPI)
// err.error => pokepaylib.Responses.BankError{}
// err.statusCode => int
} catch …
```

Pokepay client with custom domain

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Account/CreateAccountSevenElevenAtmSession.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/SevenElevenAtmSession.java

For [Seven Eleven ATM topup project](https://github.com/pokepay/pokepay-server/pull/2947)
Added:
- CreateAccountSevenElevenAtmSessions (Request)
- SevenElevenAtmSession (Response)

Added Seven Eleven Atm Session Request/Response

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithBill.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithCashtray.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithJwt.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Parameters/TransactionStrategy.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/CashtrayAttempt.java

[#3105](https://github.com/pokepay/pokepay-server/issues/3105)

Add strategy parameter

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Parameters/TransactionStrategy.java
sample/src/main/java/jp/pokepay/pokepay/LowLevelAPITests.java

[3105](https://github.com/pokepay/pokepay-server/issues/3105)
https://coilinc.slack.com/archives/C030N0QMCG7/p1665705788945019?thread_ts=1664161368.112889&cid=C030N0QMCG7

Add strategy parameter hotfix

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Check/CreateCheck.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Request.java
sample/src/main/java/jp/pokepay/pokepay/LowLevelAPITests.java

[#3149](https://github.com/pokepay/pokepay-server/issues/3149)

Add expiresAt parameter for create check

---

pokepaylib/build.gradle

Version matching update with flutter SDK.

Version update to 2.0.0

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java

[#3334](https://github.com/pokepay/pokepay-server/issues/3334)

Custom domain fallback for scanning token

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithBill.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithCashtray.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithCheck.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Transaction/CreateTransactionWithCpm.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Pokepay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/Account.java

Added point debt parameter to Account Response (ref: [3290](https://github.com/pokepay/pokepay-server/pull/3290))
Added request id parameter to `CreateTransactionWithBill`, `CreateTransactionWithCashtray`, `CreateTransactionWithCheck` and `CreateTransactionWithCpm`

Add point debt and request Id

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/User/GetUserWithAuthFactors.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/UserWithAuthFactors.java

[#3695](https://github.com/pokepay/pokepay-server/issues/3695)

User with auth factors

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/User/BankPayTopUp.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/User/CreateBankPay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/User/GetBankPay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/BankPay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/BankPayRedirectUrl.java

https://www.notion.so/pocket-change/MobileSDK-BankPay-API-3967a62dc34745369946e3c7855abe43?pvs=4

BankPay API

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Account/IdentifyIndividual.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Parameters/Gender.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/IdentificationMatch.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/IdentificationResult.java

https://coilinc.slack.com/archives/CSDAE8S05/p1694430828320339

IdentifyIndividual API for My Number

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/PrivateMoney.java

https://app.clickup.com/t/85ztx8nkp

Add `can_use_c2c_transfer` to PrivateMoney response

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/Account/GetAccountCampaignPointAmounts.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/AccountCampaignPointAmounts.java

https://app.clickup.com/t/85zu043pc

GetAccountCampaignPointAmounts endpoint

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/User/CreateBankPay.java
pokepaylib/src/main/java/jp/pokepay/pokepaylib/Responses/BankPayRedirectUrl.java

https://app.clickup.com/t/85zu2x1yh

createBankPay: Add `kana` to params and `paytreeCustomerNumber` to response

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/User/DeleteBankPay.java

[Related slack thread](https://coilinc.slack.com/archives/CSDAE8S05/p1701249266505829)
https://github.com/pokepay/pokepay-server/pull/4237
https://github.com/pokepay/pokepay-server/blob/master/docs/api/bank.yaml#L1255

DeleteBankPay endpoint

---

pokepaylib/src/main/java/jp/pokepay/pokepaylib/BankAPI/User/BankPayTopUp.java

The changes correspond to the following.
https://github.com/pokepay/pokepay-server/pull/4295/files#diff-21dd2bf452e9669fee785936a638e47b960437a5276b0df4ad91c8305d82c70f

Add request_id in POST /users/:uuid/banks/topup

---

pokepaylib/build.gradle
pokepaylib/src/main/java/jp/pokepay/pokepaylib/ExternalServiceAPI/Veritrans/GetVeritransToken.java
pokepaylib/src/test/java/jp/pokepay/pokepaylib/CreateCreditCardTest.java
pokepaylib/src/test/java/jp/pokepay/pokepaylib/GetVeritransTokenTest.java
sample/src/main/java/jp/pokepay/pokepay/CreditCardActivity.java

https://app.clickup.com/t/86epn6mrw?comment=90180052979265

Add cardholderName param to GetVeritransToken
